const LOCAL_LOGO_CODES = new Set([
  "3S", "3U", "5J", "5X", "5Y", "7C", "7L", "8M", "9C",
  "9G", "AA", "AC", "AF", "AI", "AK", "AM", "AR", "AS",
  "AT", "AY", "B7", "BA", "BI", "BR", "BX", "C6", "C8",
  "CA", "CF", "CI", "CK", "CM", "CV", "CX", "CZ", "D0",
  "D7", "DL", "DV", "EK", "ET", "EY", "FD", "FM", "FX",
  "GA", "GG", "GI", "GS", "HA", "HH", "HO", "HU", "HX",
  "HY", "I9", "IB", "IT", "JG", "JL", "JQ", "JT", "JU",
  "K4", "KC", "KE", "KJ", "KL", "KN", "KQ", "KU", "LA",
  "LD", "LH", "LJ", "LO", "LX", "LY", "M0", "M7", "MF",
  "MH", "MM", "MP", "MS", "MU", "NH", "NQ", "NX", "NZ",
  "O3", "OD", "OM", "OZ", "PO", "PR", "QF", "QR", "QV",
  "QW", "RF", "RS", "SC", "SK", "SL", "SQ", "SV", "T5",
  "TG", "TK", "TN", "TP", "TR", "TW", "UA", "UL", "UO",
  "UX", "VA", "VJ", "VN", "VS", "VZ", "WB", "WE", "WS",
  "WY", "XY", "YG", "YP", "Z2", "ZA", "ZE", "ZG", "ZH"
]);

// 인천공항 공식 정기편 목록, 출발 API의 실제 운항사 및 코드쉐어 항공사 코드.
export const AIRLINES = {
  "3S": { name: "AeroLogic", icao: "3SX" },
  "3U": { name: "Sichuan Airlines", icao: "CSC" },
  "5J": { name: "Cebu Pacific", icao: "CEB" },
  "5X": { name: "UPS Airlines", icao: "UPS" },
  "5Y": { name: "Atlas Air", icao: "GTI" },
  "7C": { name: "Jeju Air", icao: "JJA" },
  "7L": { name: "Silk Way West Airlines", icao: "AZG" },
  "8M": { name: "Myanmar Airways International", icao: "MMA" },
  "9C": { name: "Spring Airlines", icao: "CQH" },
  "9G": { name: "Sun PhuQuoc Airways", icao: "SPQ" },
  AA: { name: "American Airlines", icao: "AAL" },
  AC: { name: "Air Canada", icao: "ACA" },
  AF: { name: "Air France", icao: "AFR" },
  AI: { name: "Air India", icao: "AIC" },
  AK: { name: "AirAsia", icao: "AXM" },
  AM: { name: "Aeromexico", icao: "AMX" },
  AR: { name: "Aerolineas Argentinas", icao: "ARG" },
  AS: { name: "Alaska Airlines", icao: "ASA" },
  AT: { name: "Royal Air Maroc", icao: "RAM" },
  AY: { name: "Finnair", icao: "FIN" },
  B7: { name: "UNI Air", icao: "UIA" },
  BA: { name: "British Airways", icao: "BAW" },
  BI: { name: "Royal Brunei Airlines", icao: "RBA" },
  BR: { name: "EVA Air", icao: "EVA" },
  BX: { name: "Air Busan", icao: "ABL" },
  C6: { name: "Centrum Air", icao: "MFX" },
  C8: { name: "Cargolux Italia", icao: "ICV" },
  CA: { name: "Air China", icao: "CCA" },
  CF: { name: "China Postal Airlines", icao: "CYZ" },
  CI: { name: "China Airlines", icao: "CAL" },
  CK: { name: "China Cargo Airlines", icao: "CKK" },
  CM: { name: "Copa Airlines", icao: "CMP" },
  CV: { name: "Cargolux", icao: "CLX" },
  CX: { name: "Cathay Pacific", icao: "CPA" },
  CZ: { name: "China Southern Airlines", icao: "CSN" },
  D0: { name: "DHL Air", icao: "DHK" },
  D7: { name: "AirAsia X", icao: "XAX" },
  DL: { name: "Delta Air Lines", icao: "DAL" },
  DV: { name: "SCAT Airlines", icao: "VSV" },
  EK: { name: "Emirates", icao: "UAE" },
  ET: { name: "Ethiopian Airlines", icao: "ETH" },
  EY: { name: "Etihad Airways", icao: "ETD" },
  FD: { name: "Thai AirAsia", icao: "AIQ" },
  FM: { name: "Shanghai Airlines", icao: "CSH" },
  FX: { name: "FedEx", icao: "FDX" },
  GA: { name: "Garuda Indonesia", icao: "GIA" },
  GG: { name: "Sky Lease Cargo", icao: "GGC" },
  GI: { name: "Air Central", icao: "LHA" },
  GS: { name: "Tianjin Airlines", icao: "GCR" },
  HA: { name: "Hawaiian Airlines", icao: "HAL" },
  HH: { name: "Qanot Sharq", icao: "QNT" },
  HO: { name: "Juneyao Air", icao: "DKH" },
  HU: { name: "Hainan Airlines", icao: "CHH" },
  HX: { name: "Hong Kong Airlines", icao: "CRK" },
  HY: { name: "Uzbekistan Airways", icao: "UZB" },
  I9: { name: "Central Airlines", icao: "HLF" },
  IB: { name: "Iberia", icao: "IBE" },
  IT: { name: "Tigerair Taiwan", icao: "TTW" },
  JG: { name: "JD Airlines", icao: "JDL" },
  JL: { name: "Japan Airlines", icao: "JAL" },
  JQ: { name: "Jetstar", icao: "JST" },
  JT: { name: "Lion Air", icao: "LNI" },
  JU: { name: "Air Serbia", icao: "ASL" },
  K4: { name: "Kalitta Air", icao: "CKS" },
  KC: { name: "Air Astana", icao: "KZR" },
  KE: { name: "Korean Air", icao: "KAL" },
  KJ: { name: "AirZeta", icao: "AIH" },
  KL: { name: "KLM", icao: "KLM" },
  KN: { name: "China United Airlines", icao: "CUA" },
  KQ: { name: "Kenya Airways", icao: "KQA" },
  KU: { name: "Kuwait Airways", icao: "KAC" },
  LA: { name: "LATAM Airlines", icao: "LAN" },
  LD: { name: "Air Hong Kong", icao: "AHK" },
  LH: { name: "Lufthansa", icao: "DLH" },
  LJ: { name: "Jin Air", icao: "JNA" },
  LO: { name: "LOT Polish Airlines", icao: "LOT" },
  LX: { name: "SWISS", icao: "SWR" },
  LY: { name: "El Al", icao: "ELY" },
  M0: { name: "Aero Mongolia", icao: "MNG" },
  M7: { name: "MasAir", icao: "MAA" },
  MF: { name: "Xiamen Air", icao: "CXA" },
  MH: { name: "Malaysia Airlines", icao: "MAS" },
  MM: { name: "Peach", icao: "APJ" },
  MP: { name: "Martinair", icao: "MPH" },
  MS: { name: "Egyptair", icao: "MSR" },
  MU: { name: "China Eastern Airlines", icao: "CES" },
  NH: { name: "All Nippon Airways", icao: "ANA" },
  NQ: { name: "Air Japan", icao: "AJX" },
  NX: { name: "Air Macau", icao: "AMU" },
  NZ: { name: "Air New Zealand", icao: "ANZ" },
  O3: { name: "SF Airlines", icao: "CSS" },
  OD: { name: "Batik Air Malaysia", icao: "MXD" },
  OM: { name: "MIAT Mongolian Airlines", icao: "MGL" },
  OZ: { name: "Asiana Airlines", icao: "AAR" },
  PO: { name: "Polar Air Cargo", icao: "PAC" },
  PR: { name: "Philippine Airlines", icao: "PAL" },
  QF: { name: "Qantas", icao: "QFA" },
  QR: { name: "Qatar Airways", icao: "QTR" },
  QV: { name: "Lao Airlines", icao: "LAO" },
  QW: { name: "Qingdao Airlines", icao: "QDA" },
  RF: { name: "Aero K", icao: "EOK" },
  RS: { name: "Air Seoul", icao: "ASV" },
  SC: { name: "Shandong Airlines", icao: "CDG" },
  SK: { name: "SAS", icao: "SAS" },
  SL: { name: "Thai Lion Air", icao: "TLM" },
  SQ: { name: "Singapore Airlines", icao: "SIA" },
  SV: { name: "Saudia", icao: "SVA" },
  T5: { name: "Turkmenistan Airlines", icao: "TUA" },
  TG: { name: "Thai Airways", icao: "THA" },
  TK: { name: "Turkish Airlines", icao: "THY" },
  TN: { name: "Air Tahiti Nui", icao: "THT" },
  TP: { name: "TAP Air Portugal", icao: "TAP" },
  TR: { name: "Scoot", icao: "TGW" },
  TW: { name: "T'way Air", icao: "TWB" },
  UA: { name: "United Airlines", icao: "UAL" },
  UL: { name: "SriLankan Airlines", icao: "ALK" },
  UO: { name: "HK Express", icao: "HKE" },
  UX: { name: "Air Europa", icao: "AEA" },
  VA: { name: "Virgin Australia", icao: "VOZ" },
  VJ: { name: "VietJet Air", icao: "VJC" },
  VN: { name: "Vietnam Airlines", icao: "HVN" },
  VS: { name: "Virgin Atlantic", icao: "VIR" },
  VZ: { name: "Thai VietJet Air", icao: "TVJ" },
  WB: { name: "RwandAir", icao: "RWD" },
  WE: { name: "Parata Air", icao: "PTA" },
  WS: { name: "WestJet", icao: "WJA" },
  WY: { name: "Oman Air", icao: "OMA" },
  XY: { name: "flynas", icao: "KNE" },
  YG: { name: "YTO Cargo Airlines", icao: "HYT" },
  YP: { name: "Air Premia", icao: "APZ" },
  Z2: { name: "Philippines AirAsia", icao: "APG" },
  ZA: { name: "Sky Angkor Airlines", icao: "SWM" },
  ZE: { name: "Eastar Jet", icao: "ESR" },
  ZG: { name: "ZIPAIR", icao: "TZP" },
  ZH: { name: "Shenzhen Airlines", icao: "CSZ" }
};

export const normalizeAirlineCode = (value) => String(value || "").slice(0, 2).toUpperCase();

export const getAirline = (value) => {
  const code = normalizeAirlineCode(value);
  const airline = AIRLINES[code];
  return {
    code: code || "--",
    name: airline?.name || `${code || "Unknown"} airline`,
    icao: airline?.icao || null,
    logo: LOCAL_LOGO_CODES.has(code) ? `/airlines/v1/${code.toLowerCase()}.png` : null
  };
};
