const LOCAL_LOGO_CODES = new Set([
  "5J", "5Y", "7C", "AA", "AC", "AF", "AI", "AM", "AY",
  "BR", "BX", "CA", "CI", "CV", "CX", "CZ", "DL", "EK", "ET",
  "FM", "GA", "GS", "HX", "JQ", "KC", "KE", "KJ", "KL", "LH",
  "LJ", "LO", "MF", "MH", "MM", "MU", "NX", "O3", "OM", "OZ",
  "PR", "QR", "QV", "QW", "RF", "RS", "SC", "SK", "SQ", "TG",
  "TK", "TR", "TW", "UA", "UO", "VJ", "VN", "VS", "YP", "ZE",
  "ZG", "ZH"
]);

// 인천공항 출발 API의 실제 운항사와 FR24 인천공항 현황에서 확인한 항공사 코드.
export const AIRLINES = {
  "3U": { name: "Sichuan Airlines", icao: "CSC" },
  "5J": { name: "Cebu Pacific", icao: "CEB" },
  "5Y": { name: "Atlas Air", icao: "GTI" },
  "7C": { name: "Jeju Air", icao: "JJA" },
  "8M": { name: "Myanmar Airways International", icao: "MMA" },
  "9C": { name: "Spring Airlines", icao: "CQH" },
  AA: { name: "American Airlines", icao: "AAL" },
  AC: { name: "Air Canada", icao: "ACA" },
  AF: { name: "Air France", icao: "AFR" },
  AI: { name: "Air India", icao: "AIC" },
  AK: { name: "AirAsia", icao: "AXM" },
  AM: { name: "Aeromexico", icao: "AMX" },
  AS: { name: "Alaska Airlines", icao: "ASA" },
  AY: { name: "Finnair", icao: "FIN" },
  BI: { name: "Royal Brunei Airlines", icao: "RBA" },
  BR: { name: "EVA Air", icao: "EVA" },
  BX: { name: "Air Busan", icao: "ABL" },
  C6: { name: "My Freighter", icao: "MFX" },
  CA: { name: "Air China", icao: "CCA" },
  CI: { name: "China Airlines", icao: "CAL" },
  CV: { name: "Cargolux", icao: "CLX" },
  CX: { name: "Cathay Pacific", icao: "CPA" },
  CZ: { name: "China Southern Airlines", icao: "CSN" },
  D7: { name: "AirAsia X", icao: "XAX" },
  DL: { name: "Delta Air Lines", icao: "DAL" },
  DV: { name: "SCAT Airlines", icao: "VSV" },
  EK: { name: "Emirates", icao: "UAE" },
  ET: { name: "Ethiopian Airlines", icao: "ETH" },
  EY: { name: "Etihad Airways", icao: "ETD" },
  FM: { name: "Shanghai Airlines", icao: "CSH" },
  GA: { name: "Garuda Indonesia", icao: "GIA" },
  GS: { name: "Tianjin Airlines", icao: "GCR" },
  HH: { name: "Qanot Sharq", icao: "QNT" },
  HU: { name: "Hainan Airlines", icao: "CHH" },
  HX: { name: "Hong Kong Airlines", icao: "CRK" },
  HY: { name: "Uzbekistan Airways", icao: "UZB" },
  IT: { name: "Tigerair Taiwan", icao: "TTW" },
  JQ: { name: "Jetstar", icao: "JST" },
  KC: { name: "Air Astana", icao: "KZR" },
  KE: { name: "Korean Air", icao: "KAL" },
  KJ: { name: "AirZeta", icao: "AIH" },
  KL: { name: "KLM", icao: "KLM" },
  KN: { name: "China United Airlines", icao: "CUA" },
  LH: { name: "Lufthansa", icao: "DLH" },
  LJ: { name: "Jin Air", icao: "JNA" },
  LO: { name: "LOT Polish Airlines", icao: "LOT" },
  LX: { name: "SWISS", icao: "SWR" },
  M0: { name: "Aero Mongolia", icao: "MNG" },
  MF: { name: "Xiamen Air", icao: "CXA" },
  MH: { name: "Malaysia Airlines", icao: "MAS" },
  MM: { name: "Peach", icao: "APJ" },
  MU: { name: "China Eastern Airlines", icao: "CES" },
  NX: { name: "Air Macau", icao: "AMU" },
  O3: { name: "SF Airlines", icao: "CSS" },
  OD: { name: "Batik Air Malaysia", icao: "MXD" },
  OM: { name: "MIAT Mongolian Airlines", icao: "MGL" },
  OZ: { name: "Asiana Airlines", icao: "AAR" },
  PR: { name: "Philippine Airlines", icao: "PAL" },
  QR: { name: "Qatar Airways", icao: "QTR" },
  QV: { name: "Lao Airlines", icao: "LAO" },
  QW: { name: "Qingdao Airlines", icao: "QDA" },
  RF: { name: "Aero K", icao: "EOK" },
  RS: { name: "Air Seoul", icao: "ASV" },
  SC: { name: "Shandong Airlines", icao: "CDG" },
  SK: { name: "SAS", icao: "SAS" },
  SQ: { name: "Singapore Airlines", icao: "SIA" },
  T5: { name: "Turkmenistan Airlines", icao: "TUA" },
  TG: { name: "Thai Airways", icao: "THA" },
  TK: { name: "Turkish Airlines", icao: "THY" },
  TR: { name: "Scoot", icao: "TGW" },
  TW: { name: "T'way Air", icao: "TWB" },
  UA: { name: "United Airlines", icao: "UAL" },
  UL: { name: "SriLankan Airlines", icao: "ALK" },
  UO: { name: "HK Express", icao: "HKE" },
  VJ: { name: "VietJet Air", icao: "VJC" },
  VN: { name: "Vietnam Airlines", icao: "HVN" },
  VS: { name: "Virgin Atlantic", icao: "VIR" },
  VZ: { name: "Thai VietJet Air", icao: "TVJ" },
  WS: { name: "WestJet", icao: "WJA" },
  YP: { name: "Air Premia", icao: "APZ" },
  ZA: { name: "Sky Angkor Airlines", icao: "SWM" },
  ZE: { name: "Eastar Jet", icao: "ESR" },
  ZG: { name: "ZIPAIR", icao: "TZP" },
  ZH: { name: "Shenzhen Airlines", icao: "CSZ" }
};

export const normalizeAirlineCode = (value) => String(value || "").slice(0, 2).toUpperCase();

export const getAirline = (value) => {
  const code = normalizeAirlineCode(value);
  const airline = AIRLINES[code];
  return {
    code: code || "--",
    name: airline?.name || `${code || "Unknown"} airline`,
    icao: airline?.icao || null,
    logo: LOCAL_LOGO_CODES.has(code) ? `/airlines/v1/${code.toLowerCase()}.png` : null
  };
};
